# Generated by Django 5.1.5 on 2025-03-26 10:59

import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='products/thumbnails'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(null=True, upload_to='shops/'),
        ),
        migrations.AddField(
            model_name='shop',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='shops/thumbnails'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='users/thumbnails'),
        ),
    ]
