# Generated by Django 5.1.5 on 2025-03-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image_product_thumbnail_shop_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtoken',
            old_name='token',
            new_name='key',
        ),
    ]
